services:
  - type: web
    name: traffic_backend
    env: python
    pythonVersion: 3.12.10
    buildCommand: pip install -r requirements.txt
    # startCommand: gunicorn traffic_main.wsgi:application --bind 0.0.0.0:8000
    startCommand: python --version && gunicorn traffic_main.wsgi:application --bind 0.0.0.0:8000
