services:
  - type: web
    name: traffic_backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python --version && gunicorn traffic_main.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10 # 強制指定 Python 版本
      # 可在此添加其他環境變數，例如資料庫連線設定
