services:
  - type: web
    name: traffic_backend
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn traffic_project.wsgi --bind 0.0.0.0:8000
