# Generated by Django 5.2.3 on 2025-09-13 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主鍵ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, help_text='一組四路口資料歸為同一批', unique=True, verbose_name='批次唯一識別碼')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='資料接收或預測時間')),
                ('east_west_seconds', models.IntegerField(blank=True, help_text='模型預測的東西向最大綠燈秒數', null=True, verbose_name='東西向最大綠燈秒數')),
                ('south_north_seconds', models.IntegerField(blank=True, help_text='模型預測的南北向最大綠燈秒數', null=True, verbose_name='南北向最大綠燈秒數')),
            ],
            options={
                'verbose_name': '資料組主表',
                'verbose_name_plural': '資料組主表',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主鍵ID')),
                ('VD_ID', models.CharField(choices=[('VLRJX20', '往東 (VLRJX20)'), ('VLRJM60', '往西 (VLRJM60)'), ('VLRJX00', '往南/往北 (VLRJX00)')], max_length=10, verbose_name='路口偵測器ID')),
                ('DayOfWeek', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], verbose_name='星期')),
                ('Hour', models.IntegerField(help_text='0-23', verbose_name='時')),
                ('Minute', models.IntegerField(help_text='0-59', verbose_name='分')),
                ('Second', models.IntegerField(help_text='0-59', verbose_name='秒')),
                ('IsPeakHour', models.BooleanField(help_text='True=尖峰時段, False=非尖峰時段', verbose_name='是否尖峰時段')),
                ('LaneID', models.IntegerField(verbose_name='車道編號')),
                ('LaneType', models.IntegerField(verbose_name='車道類型')),
                ('Speed', models.FloatField(verbose_name='平均速率')),
                ('Occupancy', models.FloatField(verbose_name='車道佔有率')),
                ('Volume_M', models.IntegerField(verbose_name='中型車流量')),
                ('Speed_M', models.FloatField(verbose_name='中型車速率')),
                ('Volume_S', models.IntegerField(verbose_name='小型車流量')),
                ('Speed_S', models.FloatField(verbose_name='小型車速率')),
                ('Volume_L', models.IntegerField(verbose_name='大型車流量')),
                ('Speed_L', models.FloatField(verbose_name='大型車速率')),
                ('Volume_T', models.IntegerField(default=0, help_text='特種車流量，預設為0', verbose_name='特種車流量')),
                ('Speed_T', models.FloatField(default=0.0, help_text='特種車速率，預設為0.0', verbose_name='特種車速率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to='traffic_signal.group', verbose_name='關聯到資料組主表')),
            ],
            options={
                'verbose_name': '路口明細表',
                'verbose_name_plural': '路口明細表',
                'ordering': ['group', 'VD_ID', 'LaneID'],
            },
        ),
    ]
